* SoapyRX

An SDR receiver built on [[https://github.com/pothosware/SoapySDR/wiki][SoapySDR]].

The scope of this tool is to handle signal acquisition from an SDR. Using
SoapySDR as backend, it supports every SDR supported by the latter -- as long
as the corresponding module is installed. It is not meant to process datasets
of signals (/e.g./, conversion, alignment, normalization).

- Features ::
  - One-shot record-plot-cut-save from the command-line.
  - Server mode controlled from a client (local socket).
  - Multiple synchronized SDRs controlled in parallel.
  - Display basic signal visualization (amplitude, phase rotation, time-domain, frequency-domain).
  - Perform single-signal operations (/e.g./, interactive cutting).
  - Use complex numbers (I/Q) for storage (=numpy.complex64=).

* Installation

1. Install [[https://github.com/pothosware/SoapySDR/wiki][SoapySDR]] using distribution packages or sources.

2. Clone SoapyRX repository and install it using using [[https://pypi.org/project/pip/][Pip]]:
   #+begin_src bash :eval never
   git clone https://github.com/pierreay/soapyrx.git
   cd soapyrx && pip install --user .
   #+end_src

* Usage

TODO: Usage demonstration.

* Files

TODO: Link to main files.
